### ISSUE TITLE
libretro: Gambatte not working

### ISSUE THREAD

**Issue by deltabeard** [deltabeard/Haiyajan#18]

**Comment by petrutoader** [comment]
Thanks for creating the issue, here's the command line output:

`ERROR: GAMBATTE: [Gambatte]: Cannot dupe frames!`

Tested on Haiyajan's Pre-release version 0.1 (6a1be3d).

**Comment by deltabeard** [comment]
Thanks for the info.
The error is from https://github.com/libretro/gambatte-libretro/blob/fde2713ad1145ce306f197535a40f6ffbd012343/libgambatte/libretro/libretro.cpp#L1470 in gambatte. Frame duping support shouldn't be difficult to add support for, since I think it simply shows the previously rendered frame again.
